sonar.projectKey=LevonGabrielyan04_PingKit
sonar.organization=levongabrielyan04
sonar.projectName=PingKit

sonar.sources=app,bootstrap,config,database,resources,routes
sonar.tests=tests
sonar.exclusions=bootstrap/cache/**,storage/**,resources/js/actions/**,resources/js/routes/**,resources/js/wayfinder/**
sonar.sourceEncoding=UTF-8
